version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels: ["area:build"]
    groups:
      cargo:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: ["area:build"]
    groups:
      actions:
        patterns: ["*"]
        update-types: [minor, patch]
